repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
    -   id: codespell
        types_or: [python, markdown]
        additional_dependencies: [tomli]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff
        args: ["check", "--exit-non-zero-on-fix"]
        require_serial: true
        language: system
        types: [python]
        exclude: examples/
